import type { Metadata } from "next";

import "./globals.css";
import dynamic from "next/dynamic";
import Header from "@/src/components/atoms/Header";

const Navbar = dynamic(() => import("@/src/components/sections/Navbar"));
const Footer = dynamic(() => import("@/src/components/sections/Footer"));

// Definisci i metadata di base
const baseMetadata: Metadata = {
  title: "MyPortfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/svg/logo.svg",
  },
};

// Funzione per generare i metadata
export const generateMetadata = (): Metadata => {
  return baseMetadata;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <Header metadata={generateMetadata()} />
        <body className="antialiased min-h-screen flex flex-col font-mono bg-gray-50">
          <Navbar />
          <main className="flex-grow mt-20 mb-20 px-4">{children}</main>
          <Footer />
        </body>
      </html>
    </>
  );
}
